export const UPDATE_SETTINGS = 'UPDATE SETTINGS';
export const FETCH_SETTINGS = 'FETCH SETTINGS';
export const FETCH_EVENTS = 'FETCH EVENTS';
export const UPDATE_EVENT = 'UPDATE EVENT';
export const UPDATE_MARKET = 'UPDATE MARKETS';
export const UPDATE_OUTCOMES = 'UPDATE OUTCOMES';